PROGRAM DECAY
IMPLICIT NONE
REAL::T,PERCENTAGE,RATIO,LAMDA
LAMDA = 0.00012097
WRITE(*,*)"ENTER PERCENTAGE OF REMAINING CARBON  (IN %)"
READ(*,*)PERCENTAGE
RATIO=PERCENTAGE/100
T=(-1)*(1/LAMDA)*(LOG(RATIO))
WRITE(*,*)"T",T, 'SEC'
END PROGRAM DECAY
