program SQ
implicit none
integer::i
reAL,DIMENSION(10)::VALUE=[(I,I=1,10,1)]
REAL,DIMENSION(10):: SQUARE_ROOT
DO I =1,10,1
SQUARE_ROOT(I)=SQRT(VALUE(I))
END DO
DO I=1,10,1
WRITE(*,*)"VALUE(I)",SQUARE_ROOT(I)
END DO
END PROGRAM SQ
